spring.application.name=petisos-backend
# Configuración del servidor
server.port=8080

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/petisos_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:admin}

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará/actualizará la estructura de tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
